INGInious/INGInious

doc/install_doc/installation.rst, doc/install_doc/lti.rst, inginious-lti-wsgi.py, inginious-webapp-wsgi.py
Patches to add WSGI scripts and documentation to show how to use those (as well as some troubleshoot for LTI).
The configuration of the WSGI scripts leaves something to be desired (editing the file) but it appears it's not easy to pass in this information from the Apache config file.
=> Patch add wsgi

inginious/frontend/webapp/plugins/auth/ldap_auth.py
PR #190 did not LGTM.
@anthonygego can you test (;-)) this commit asap?
=> Fix changes of #190

inginious-agent-docker, inginious-agent-mcq, inginious/agent/docker_agent.py, inginious/agent/mcq_agent.py, inginious/common/base.py, inginious/common/course_factory.py, inginious/common/entrypoints.py, inginious/common/filesystems/local.py, inginious/common/filesystems/provider.py, inginious/common/task_factory.py, inginious/common/tasks.py, inginious/common/tests/TestCourse.py, inginious/common/tests/TestTask.py, inginious/frontend/common/arch_helper.py, inginious/frontend/webapp/app.py, inginious/frontend/webapp/pages/course_admin/task_edit.py, inginious/frontend/webapp/pages/course_admin/task_edit_file.py, inginious/frontend/webapp/pages/tasks.py, inginious/frontend/webapp/templates/course_admin/edit_tabs/files.html, setup.py, utils/check_task_description/inginious-check-task, utils/task_converter/inginious-old-task-converter, utils/task_tester/inginious-test-task
Modularize the access to the filesystem.
=> Filesystem providers

inginious/frontend/common/static/icons/google-icon.svg, inginious/frontend/webapp/plugins/auth/google_auth.py
This PR adds Google as an authentication method. It also supports a domain option to allow restricting the authentication to a specific domain.
Note: I'm not sure if using the logo without the rest of the button is allowed by their branding guidelines (and I think this applies to the rest of the sign-in buttons as well).
=> Add Google auth

inginious/frontend/plugins/auth/google_auth.py
This is great you added the Google OAuth plugin. I added support to restrict it to allow a defined domain (e.g. 'colorado.edu').
=> Added domain for Google OAuth plugin

base-containers/base/inginious/input.py, inginious/frontend/pages/tasks.py, inginious/frontend/submission_manager.py, inginious/frontend/tasks.py, inginious/frontend/templates/course_admin/edit_tabs/basic.html, inginious/frontend/templates/task.html
This add a way to generate inputs randoms for exercises. With this mechanism, each student can have a different exercises, avoiding copy/paste by students.
Here is an example of task using random inputs: https://www.dropbox.com/s/8m932u0s35tssdb/task_input_random_01.zip?dl=1
=> Input random

doc/dev_doc/plugins.rst, inginious/frontend/task_problems.py, inginious/frontend/templates/task.html
The username is used as seed, as no particular security is needed here: we only need that each student has a different seed, and knowing the seed beforehand will not help them to guess the answers :-)
=> Use a fixed seed (based on username) to shuffle MCQs

inginious-agent-docker, inginious-agent-mcq, inginious-backend, inginious/agent/__init__.py, inginious/agent/docker_agent/__init__.py, inginious/backend/backend.py, inginious/frontend/app.py, inginious/frontend/arch_helper.py
Log most of the exceptions that are not yet logged, and make _do_ping more robust to failures.
=> Make backend/agent more robust

doc/teacher_doc/common.rst, doc/teacher_doc/create_task.rst, inginious/agent/docker_agent/__init__.py, inginious/agent/docker_agent/_docker_interface.py
Files stored in the subdirectory "common" of a course are available to all tasks, inside the container, at the path "/course/common". This directory is only mounted in the grading container.
Files stored in the subdirectory "common_student" of a course are available to all tasks, inside the container, at the path "/course/common_student". This directory is mounted in the grading container and in student containers.
All these folder are read-only inside the containers.
=> Share the folder "course/common" and "course/common_student" inside the containers

inginious/frontend/templates/course_admin/submissions.html
Add one digit accuracy for all tags.
Add non-ronded value for rare tags.
=> Better visualization of statistics in submission viewer

inginious/common/asyncio_utils.py, inginious/frontend/cookieless_app.py, inginious/frontend/session_mongodb.py
this commit adds the support for python3.7 and corrects problem due to the non compatibility of web.py with python3.7
=> add support for python3.7

doc/commands_doc/inginious-install.rst, doc/commands_doc/inginious-webapp.rst, doc/dev_doc/how_to_extend.rst, doc/dev_doc/plugins.rst, doc/dev_doc/understand_inginious.rst, doc/install_doc/config_reference.rst, doc/install_doc/installation.rst, doc/install_doc/troubleshooting.rst, doc/teacher_doc/best_practices.rst, doc/teacher_doc/what_is_inginious.rst
More typos have yet to come ;-)
=> Fixing some documentation typos and errors.

inginious/frontend/plugins/auth/google_auth.py
The Google Oauth scope attributes changed. Using the new attributes fixes the login issues.
=> Google Oauth Scope Attributes changes

inginious/frontend/pages/preferences/profile.py
This PR fixes some issues/bugs while saving the profile, here are the problems fixed:
1. When you register using _social authentication_ and then try to add a custom password, the application says your profile was saved correctly with the new password but it wasn't updated actually.
This is a problem when you want to update your bindings, as you cannot remove them because you need a password but you cannot update the password. 
**The fix proposed for this is to check the length of new password rather than the old password so that way we know when the user wants to update the password.**
2. If the name is updated, the current session is not updated with the new name. Also, it doesn't check if the new name is empty.
3. If you update all fields at the same time (password, name and language), …
=> Fix some issues saving profile

.gitignore, doc/commands_doc/inginious-autotest.rst, inginious-autotest, inginious/common/tags.py, inginious/common/tasks.py, inginious/frontend/parsable_text.py, inginious/frontend/tasks.py, setup.py
Non final version of autotesting script for code checking
=> Autotest Script

doc/install_doc/config_reference.rst, doc/teacher_doc/random.rst, doc/teacher_doc/task_file.rst
=> small doc fixes

inginious/frontend/pages/tasks.py
When loading long chains of debug data, the browser load is increasing
drastically. This is either due to an excessive amount of prints or
to the binary value of uploaded files that are printed out in the debug
dialog. This commit cuts all the chains that exceeds 1000 characters
(if this is a string) or bytes (if this is a byte chain).
=> Cut long chains in task debug information

inginious/frontend/pages/tasks.py
=> get 404 in case of KeyError

inginious-autotest
This is not the most useful PR but still... related to #404
=> Pyloader warning

inginious/frontend/templates/course_admin/student_list.html
=> translating non-english word

inginious/frontend/templates/course_admin/subproblems/code.html
the place holder says C++ 
where c++ return invalid language. however cpp works.
=> fixing code language place holder

inginious/frontend/user_manager.py
I try to set usernames as None like it's specify :
> If usernames is None, data from all users will be returned.
but this goes in an error.
=> If usernames is None, data from all users will be returned. Its a lie!

inginious/client/client.py, inginious/frontend/pages/queue.py, inginious/frontend/submission_manager.py, inginious/frontend/templates/queue.html
It allows administrators to manage and review jobs and agents.
=> Add a way to kill job from the job queue

doc/install_doc/installation.rst
We learned these the hard way after an exam failing in production when there are 400+ students entering the exam.
=> Update lighttpd configurations

base-containers/base/inginious_container_api/input.py, doc/teacher_doc/run_file.rst, inginious/frontend/submission_manager.py
=> Add the submission date and time to input data

inginious/frontend/user_manager.py
This fix the issue with last submission selection for evaluation
=> add a management when submission evaluation is "last"

inginious/frontend/user_manager.py
The status have no interest for "last" submission selection.
=> [replay] Remove status filter for last submission

inginious/frontend/environment_types/docker.py
=> fix: exception if hard_time limit is set

doc/install_doc/config_reference.rst, inginious/frontend/plugins/auth/ldap_auth.py
=> Ldap auth 2020

doc/teacher_doc/run_file.rst, inginious/frontend/submission_manager.py
=> Add student emails in the submission metadata

inginious/frontend/templates/course_admin/student_list.html
This allow to get a count of students in the course.
=> adding number of students at top of students list

inginious/frontend/app.py, inginious/frontend/pages/course.py, inginious/frontend/pages/course_admin/audience_edit.py, inginious/frontend/pages/course_admin/danger_zone.py, inginious/frontend/pages/course_admin/submission.py, inginious/frontend/pages/course_admin/submissions.py, inginious/frontend/pages/course_admin/task_edit_file.py, inginious/frontend/pages/course_admin/utils.py, inginious/frontend/pages/course_register.py, inginious/frontend/pages/group.py, inginious/frontend/pages/lti.py, inginious/frontend/pages/marketplace.py, inginious/frontend/pages/marketplace_course.py, inginious/frontend/pages/preferences/bindings.py, inginious/frontend/pages/preferences/delete.py, inginious/frontend/pages/preferences/profile.py, inginious/frontend/pages/register.py, inginious/frontend/pages/social.py, inginious/frontend/pages/tasks.py, inginious/frontend/pages/utils.py, inginious/frontend/templates/forbidden.html, inginious/frontend/user_manager.py
This PR provides error messages. This replaces 404 pages when errors should be more talkative.
=> Users deserve error messages in place of 404 error.

doc/teacher_doc/task_file.rst, inginious/frontend/pages/tasks.py, inginious/frontend/static/js/task.js, inginious/frontend/submission_manager.py, inginious/frontend/templates/course_admin/edit_tabs/basic.html, inginious/frontend/templates/task.html, inginious/frontend/user_manager.py
Remove "student choice" evaluation.
=> Remove student choice option for submission

inginious/client/client.py, inginious/frontend/submission_manager.py
The callback can actually be called BEFORE the new_job function returns.
=> Fix a race condition in the submission manager

base-containers/base/bin/INGInious, inginious/backend/backend.py, inginious/client/_zeromq_client.py, inginious/client/client.py, inginious/common/asyncio_utils.py
Harden zeromq_client, and make it log its exceptions
=> An even more paranoid pirate

doc/teacher_doc/create_course.rst, inginious/frontend/courses.py, inginious/frontend/pages/api/courses.py, inginious/frontend/pages/course.py, inginious/frontend/pages/course_admin/audience_edit.py, inginious/frontend/pages/course_admin/student_list.py, inginious/frontend/pages/course_register.py, inginious/frontend/pages/courselist.py, inginious/frontend/pages/mycourses.py, inginious/frontend/pages/preferences/bindings.py, inginious/frontend/pages/tasks.py, inginious/frontend/pages/utils.py, inginious/frontend/plugins/scoreboard/__init__.py, inginious/frontend/templates/course_admin/audience_edit.html, inginious/frontend/templates/course_admin/student_list.html, inginious/frontend/templates/group.html, inginious/frontend/user_manager.py
This started as a way to solve @vvandenschrieck 's #569 and then I discovered that most of the calls to `is_registration_possible` actually did not work correctly. So I fixed everything, created a unified data structure for user info (named UserInfo in a sudden burst of creativity), updated the code mostly everywhere, and implemented a (deadly simple) regex system for the ACLs.
And documented it. TL;DR: '*' is a wildcard now.
=> Regex for the ACLs

doc/install_doc/config_reference.rst, inginious/frontend/app.py, inginious/frontend/cookieless_app.py, inginious/frontend/installer.py, inginious/frontend/plugins/auth/saml2_auth.py
This puts a default timeout of a day for the session, rather than "session", which caused some problems...
Fixes #575.
=> Add a way to configure session cookies.

inginious/frontend/static/js/common.js
The long-awaited feature in #173
=> Press ctrl+enter in CodeMirror to submit

inginious/__init__.py, inginious/frontend/app.py, inginious/frontend/static/css/INGInious.css, inginious/frontend/static/css/common.less, inginious/frontend/static/css/lti.css, inginious/frontend/templates/layout.html, setup.py
This relies on setuptools_scm, which displays the version, distance, commit hash and date. This is very useful as our local instance is almost up to date, to know exactly on which version we are.
setuptools_scm tests the pip install, then the local repository, or raise a ValueError, in which case the version string is set by hand.
The version string is displayed in the footer.
=> Displays version on footer

doc/install_doc/troubleshooting.rst, inginious/common/log.py, inginious/frontend/app.py, inginious/frontend/lti_request_validator.py, inginious/frontend/pages/lti.py
- Display oauthlib logs
- Improve global logging
- Improve troubleshooting docs
=> Improve LTI debugging

inginious/agent/docker_agent/__init__.py, inginious/agent/docker_agent/_docker_interface.py
This modification ensures that the event stream always restart if Docker shuts down, and check its state.
=> Harden event stream

configuration.example.yaml, doc/install_doc/config_reference.rst, inginious-webapp
Sorry, I'm not good with git command (again). 
So, I create a new pull request.
This pull request is about to fix X-Forwarded- headers when INGInious was running behind a reverse proxy.
using https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/.
=> add fix reverse proxy configuration

.readthedocs.yaml, setup.py
This makes, once and for all, readthedocs do the appropriate job.
=> Clean up readthedocs setup process

inginious/frontend/pages/course_admin/task_list.py, inginious/frontend/static/js/task_dispensers.js, inginious/frontend/task_dispensers/util.py
This adds a checker on the task_id when creating a new task.
It is exactly based on the same code as the checker already implemented on the subproblem_id as you can see:
Code for subproblem task id:
Code for task_id:
When the id is not valid, an alert pops and the task is not created.
=> task_id checker

inginious/frontend/task_dispensers/util.py
=> add verification to avoid blank str

inginious/frontend/pages/course_admin/task_edit.py, inginious/frontend/templates/course_admin/task_edit.html
The Jinja json function ignores OrderedDict key order and prints the dict with its keys sorted alphabetically. This uses Python json function instead to ensures the keys are kept in the right order.
=> Fix subproblems ordering in task editor

inginious/common/tasks_problems.py, inginious/frontend/static/js/studio.js, inginious/frontend/task_problems.py, inginious/frontend/templates/course_admin/subproblems/multiple_choice.html
regarding #625 this PR allows to shuffle or not choices in MCQ
=> frontend/mcq : Allowing task creator to (not) shuffle choices.

base-containers/base/inginious_container_api/run_student.py, doc/admin_doc/install_doc/create_container.rst, doc/admin_doc/install_doc/updating.rst, doc/admin_documentation.rst, doc/teacher_documentation.rst
Adding a little bit more information about the way to build or download containers images.
It was apparently causing issues to some people, I hope it is more clear now.
It is also updated with the recent corrections to the scripts.
=> building containers doc

base-containers/base/bin/_run_student_intern, base-containers/base/bin/ssh_student, base-containers/base/inginious_container_api/run_student.py, base-containers/base/inginious_container_api/ssh_student.py, base-containers/base/inginious_container_api/utils.py, doc/teacher_doc/run_file.rst, inginious/agent/docker_agent/_docker_interface.py
To ease the creation of setup / teardown scripts, a student/scripts directory is automatically mounted in the container. This directory is isolated from the student during the ssh session, allowing the teacher to put scripts files in a safe directory without worying about the student inspecting them.
Documentation was also updated.
=> adding scripts isolation

inginious/frontend/task_factory.py
Fix #741.
Regression from course and task factories refactor.
Taken from 9be0653
=> [frontend/task_factory] Add translation files back to cache date watcher

inginious/common/filesystems/local.py, inginious/common/filesystems/provider.py
This PR proposes fixes for issues found while testing the `LocalFSProvider`.
It also closes issue https://github.com/UCL-INGI/INGInious/issues/746.
=> Tests fixes

inginious/frontend/templates/course_admin/student_info.html
=> use correct id to set value of task_id

.github/workflows/ci.yml, inginious/common/tests/test_filesystem_local.py
This PR proposes unit tests for the filesystem providers using the pytest framework.
Those tests are integrated in the CI and a coverage report is stored as a GitHub artifact for offline analysis.
An alternative could be the usage of an external service such as Codecov (https://about.codecov.io/).
=> Test filesystem provider

inginious/frontend/submission_manager.py, inginious/frontend/templates/course_admin/submissions.html
=> [course_admin/submissions] last replay date

inginious/frontend/pages/course_admin/submissions.py, inginious/frontend/templates/course_admin/submissions.html
Get correct count of submissions displayed
=> Get correct count of submissions displayed

inginious/frontend/app.py, inginious/frontend/flask/mongo_sessions.py, inginious/frontend/installer.py, inginious/frontend/pages/course_admin/danger_zone.py, inginious/frontend/pages/course_admin/student_list.py, inginious/frontend/pages/course_admin/submissions.py, inginious/frontend/pages/course_admin/task_edit.py, inginious/frontend/pages/course_admin/task_list.py, inginious/frontend/pages/preferences/delete.py, inginious/frontend/pages/register.py, inginious/frontend/submission_manager.py, inginious/frontend/user_manager.py, utils/database_updater/inginious-database-update
Several major deprecations are made effective from pymongo 4.
These changes are made according to this doc : https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html.
I suggest to restrict the pymongo version of the older branches to <4 to avoid any issue.
=> [pymongo] migrate to pymongo 4

base-containers/base/Dockerfile, base-containers/base/bin/_run_student_intern
This updates the containers Linux distribution to Rocky Linux 8. Python version is updated to python 3.8
=> Update containers distribution to EL8

inginious/frontend/templates/course_admin/task_dispensers/task_buttons.html
=> adding "view task" button in admin task list.

README.rst
This commit could be squashed with 7a8002a6cd825a1c66f19a506c6eeaa1df2fa567.
=> [ci] Add coverage badge to README

inginious/frontend/static/css/INGInious.css, inginious/frontend/static/css/common.less, inginious/frontend/templates/course_admin/edit_tabs/files.html, inginious/frontend/templates/course_admin/stats.html, inginious/frontend/templates/course_admin/student_list.html, inginious/frontend/templates/course_admin/student_list_table.html, inginious/frontend/templates/course_admin/submissions.html, inginious/frontend/templates/course_admin/task_edit.html
This PR proposes some tiny update to make administration more responsive, especially on smartphone.
Most of tables overflow are now manage.
=> Review responsive

inginious/frontend/pages/course_admin/settings.py, inginious/frontend/templates/course_admin/settings.html
=> [frontend/settings] Remove useless spaces in ACL

inginious/frontend/courses.py, inginious/frontend/pages/course_admin/settings.py, inginious/frontend/templates/course_admin/settings.html
Propose an implementation for #736
=> [frontend/settings] Add deny list feature

inginious/frontend/app.py
related to #811 and issue #808
=> [Frontend] Adding Hebrew as available translation

inginious/frontend/pages/course_admin/task_edit.py, inginious/frontend/templates/course_admin/edit_tabs/basic.html
=> [templates/edit_tabs] Fix radio selection condition

inginious/agent/docker_agent/__init__.py, inginious/agent/docker_agent/_docker_interface.py
This PR proposes a solution to issue #809
=> Set FS limit to containers

inginious/frontend/parsable_text.py
=> [Frontend/Feedback] set up a dynamic length for line limit in docutils

inginious/frontend/plugins/auth/linkedin_auth.py
=> [frontend/auth plugin] Linkedin compliance fix

inginious/frontend/plugins/scoreboard/__init__.py
=> [frontend/scoreboard plugin] display username if no real name is set

inginious/frontend/pages/tasks.py
=> add - submission date to feedback

inginious/frontend/templates/course_admin/settings.html
Full review of parameters display using tabs to group them by categories.
=> [frontend/course admin]Layout course parameters

inginious/frontend/task_dispensers/combinatory_test.py
Prevent from a crash that could occur on: https://github.com/UCL-INGI/INGInious/blob/fc5bde432e8571f247538eae6bbecc493560a16a/inginious/frontend/pages/course_admin/task_edit.py#L109
=> combinatory_test now return a proper dispenser data

inginious-install, inginious/frontend/installer.py
Allows a default installation of INGInious without any user-specific configuration
=> [installer] Add default configuration flag

doc/dev_doc/internals_doc/groupes_audiences.rst, doc/dev_doc/internals_doc/groups_audiences.rst, doc/developer_documentation.rst, doc/teacher_doc/course_admin.rst, inginious/frontend/pages/course_admin/student_list.py, inginious/frontend/templates/course_admin/student_list.html
This PR have for purpose to let the teacher of the course import his audiences through a CSV file.
CSV structure is as follow:
A description, a list of students (username or mail separated by a ';'), a list of tutors (username or mail separated by a ';')
=> Audience insertion via CSV file

doc/admin_doc/install_doc/installation.rst, inginious/common/additional_field.py, inginious/common/field_types.py, inginious/frontend/courses.py, inginious/frontend/pages/course_admin/settings.py, inginious/frontend/templates/course_admin/settings.html
a) Move tags page
b) add "additional fields" feature
=> [Frontend/Course Admin] Additional fields feature

inginious/frontend/installer.py
=> [Frontend/installer] review container build feature

doc/admin_doc/install_doc/installation.rst
Review installation for Ubuntu 22.04+
=> [Documentation] Review installation for Ubuntu 22.04+

inginious-autotest, inginious/common/babel.py, inginious/common/tasks_problems.py, inginious/frontend/app.py, inginious/frontend/plugin_manager.py, inginious/frontend/task_factory.py, inginious/frontend/task_problems.py
This PR adds the feature described in #864.
=> Problem types auto-discovery

inginious-webapp, inginious-webdav
=> Move Logging initialization before get_app call

inginious/frontend/pages/course_admin/submissions.py, inginious/frontend/static/js/common.js, inginious/frontend/static/js/task_dispensers.js, inginious/frontend/task_dispensers/combinatory_test.py, inginious/frontend/templates/task_dispensers_admin/combinatory_test.html, inginious/frontend/templates/task_dispensers_admin/util_task_edit_modal.html
Pull request containing multiple small fixes  to merge before release v0.9
=> Pre-release fixes for v0.9.0

.github/workflows/ci.yml, setup.py
Fixing failing CI. Packages setuptools and setuptools-scm had incompatible versions.
=> [ci] Fix ci by fixing setuptools and setuptools-scm version

doc/what_is_inginious.rst
I was reading the documentation on how INGInious works and found a broken link that I corrected
=> Fix broken link in doc

inginious/scripts/container_update.py, pyproject.toml
fix #1062
replace the hard-coded dockerhub url with `ghcr.io/inginious/env-base` and `ghcr.io/inginious/env-default`
=> [scripts] update docker repository to ghcr.io
