inginious/frontend/webapp/static/css/INGInious.css
inginious/frontend/webapp/static/css/INGInious.less

This helps when reading stdout and stderr as it preserves line breaks and indentation.

Display debug information as <pre> formatted text.

---

inginious/frontend/lti/app.py
inginious/frontend/lti/pages/utils.py
inginious/frontend/lti/user_manager.py

the LTI standard uses "user_id" as the user identifier, but most LMS's also support ext_user_username, which is typically the unique identifier for the person (e.g. in moodle, this is the account name).
We use a SSO system with ldap + shib, and would like to have the data in the Moodle and Inginious key off the same name rather than the numeric ID of the moodle user.
grade changes back to the Moodle TC still work with this change. Users can specify lti_user_name: ext_user_username in the YAML config file.
Forgot to add a doc for it, but can do it if this patch is OK.

Patch specify lti username

---

inginious/frontend/webapp/templates/course_admin/edit_tabs/subproblem_templates.html

For the multiple choice subproblem html template a quote was missing in textarea id.

missing quotes for id in subproblem templates

---

inginious/frontend/pages/course_admin/task_edit.py

I encountered the following error when trying out the current version, when attempting to edit one of the tasks in the tutorial, after clicking "Save changes":
> Your browser returned an invalid form ('NoneType' object has no attribute 'items')
I traced it to the `tags` that were being returned via the `dict_from_prefix` method ("task_edit.py" line 211) -- it is possible that this method can return a `None`, and that seemed to be happening in my case.  This PR adds a test for `None` and sets the `tags` dict to the empty dict if it is `None`.

Tags in task_edit.py can be None, set to empty dict to avoid exception.

---

inginious/frontend/app.py
inginious/frontend/fix_webpy_cookies.py

Monkey-patch web.py to support correctly Py3, without having to fork or wait for the (critical) bug to be solved. Fixes #208. Fixes #257.

Fix web.py cookies

---

setup.py

Without an explicit encoding, install via pip fails in environments where the default encoding is ASCII.

Add explicit encoding to long_description

---

inginious/frontend/static/js/task.js
inginious/frontend/task_problems.py

Solves bug where the input fields would still be grayed out after the
end of the running task if the answer to a single-line code is
incorrect.

Fixes #338

---

inginious/frontend/pages/course_admin/task_edit.py

A YAML task description can also contains integer keys, which will be parsed as such by the YAML parser. The fix prevents an error from being raised and returns the correct value.

Fixes contains_is_html method for non-string keys

---

doc/commands.rst
doc/commands_doc/inginious-webdav.rst
doc/install_doc/config_reference.rst
doc/install_doc/installation.rst
inginious-webdav
inginious/frontend/app.py
inginious/frontend/pages/course_admin/utils.py
inginious/frontend/pages/course_admin/webdav.py
inginious/frontend/pages/utils.py
inginious/frontend/webdav.py
setup.py

Quick changes to allow clients to ask OPTIONS/PROPFIND on ``/``.
``inginious-webdav`` is quite similar to ``inginious-webapp``. Maybe they can even be merged actually.
``webdav_available`` is replaced by the use of ``webdav_host`` set in ``configuration.yaml``.

Make the webdav a standalone app

---

doc/teacher_doc/task_file.rst
inginious/frontend/accessible_time.py
inginious/frontend/pages/course_admin/task_edit.py
inginious/frontend/tasks.py
inginious/frontend/templates/course_admin/edit_tabs/basic.html
inginious/frontend/templates/task.html

Sometimes, students might be tempted to perform homeworks at the very
last moment, which can be too late. This commit implements a soft
deadline mechanism that is publicly communicated, and keep the previous
deadline as hard deadline, which is kept private but determines until
when the task is available.

Show a soft deadline for tasks

---

inginious/frontend/user_manager.py

When you try to add a student to a course but if the username in the input is empty, an exception like this is shown:
The this happens when you are in **course administration** in **students** tab, the you try adding a student but the inserted username is empty.

Fix bug adding student to a course but username is empty

---

inginious/frontend/pages/tasks.py
inginious/frontend/static/js/task.js
inginious/frontend/submission_manager.py
inginious/frontend/templates/task.html

This is done by adding a `@late` tag in the input of the submission.
Compared to #387, this PR does not duplicate the `late` field to show that a submission is late or not on the task page. This is easy at submission time (js + submission_to_json), but when statically GETting the task html page, we need to fetch the tag from the input.

Record late submission v2

---

inginious/frontend/pages/utils.py

Just a little tweak for preventing bad redirection on logout
Instead redirect to /courselist.

Redirect from logout to courselist

---

inginious/frontend/submission_manager.py

Hi! I've come across a situation where it would be nice to know which attempt is currently being graded. Of course, the database can't be accessed by the grading container (and appropriately so), so I need a way to get the value. The `@username` and `@lang` keys in the `inputdata` dictionary are very helpful. I thought I could solve my own problem with `@attempts`. I've implemented this for our course by changing the source code, but it is an older version. I have tested it and found that it works well. I thought I'd future-proof things by adding the change here so I can upgrade without a problem. I have not actually tried setting up a completely new system with this new code.
My changes are very simple. I hope you'll review them and consider including them (or something similar of your …

added @attempts value to inputdata

---

inginious/frontend/i18n/en/LC_MESSAGES/messages.po
inginious/frontend/templates/course_admin/webdav.html

Also, there's a missing translation in French, but I couldn't manage to edit the file correctly (bad encoding of the file leads to problems when using characters like 'é' or 'à').
(At least, I'm pretty sure this is a typo)

Typo in WebDav interface

---

inginious/frontend/plugins/auth/google_auth.py

In mid or late July, we started receiving errors indicating 
```
Scope has changed from "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile" to "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid"
```
This fix adds the openid as required by Google Sign-In ( https://developers.google.com/identity/protocols/googlescopes )
This resolves issue #408

fix google_auth.py authentication error

---

inginious-autotest
inginious/backend/backend.py
inginious/client/client.py
inginious/client/client_buffer.py
inginious/client/client_sync.py
inginious/common/messages.py
inginious/frontend/submission_manager.py
inginious/frontend/tests/TestParsableText.py

This PR aims at bringing a quick solution for replays with the current backend architecture and replaces the round-robin made over the available agents by a job priority based scheduling. The jobs are stored in a priority queue which is popped every time the queue update function is called. 
In order to maximize the agents occupancy, the queue is popped as many times there are agents available. If a job cannot be treated by an agent, it is pushed back into the queue with a lower priority, so that it won't be prevent other jobs to run.
Currently two priorities are used. Maybe it would be interesting to use an enum or something else and set the replay priority very low to allow new kind of jobs, and to prevent normal jobs that were put back to the queue with lower priority to become less …

Job priority based scheduling

---

inginious/frontend/templates/mycourses.html

This changes the input field to register for a course as a 'password' type rather than a plain text type. This gives a better security to the course password.

Change input field to register for a course as 'password' type

---

doc/install_doc/installation.rst

Ubuntu 17+ no longer provides the package [libzmq-dev](https://packages.ubuntu.com/search?keywords=libzmq-dev), we should use libzmq3-dev instead
Tested on Ubuntu 18.04 / 19.04

Doc update : replace libzmq-dev by libzmq3-dev

---

inginious/frontend/pages/preferences/bindings.py
inginious/frontend/plugins/auth/facebook_auth.py
inginious/frontend/plugins/auth/github_auth.py
inginious/frontend/plugins/auth/google_auth.py
inginious/frontend/plugins/auth/ldap_auth.py
inginious/frontend/plugins/auth/linkedin_auth.py
inginious/frontend/plugins/auth/saml2_auth.py
inginious/frontend/plugins/auth/twitter_auth.py
inginious/frontend/templates/mycourses.html
inginious/frontend/templates/preferences/bindings.html
inginious/frontend/user_manager.py

This PR stores the additional fields returned by auth methods in the appropriate sturcture in database. Each auth method has a custom dict to store key and values for each user.
An implementation is given for the SAML auth method. An ``additional`` dictionary is specified in the settings with ``key: value`` corresponding to an identifier you want the attribute to be accessed to. For instance : 
- plugin_module: "inginious.frontend.plugins.auth.saml2_auth"
id: uclouvain
name: "UCLouvain SSO"
...
attributes:
uid: "urn:oid:0.9.2342.19200300.100.1.1"
email: "urn:oid:0.9.2342.19200300.100.1.3"
cn: "urn:oid:2.5.4.3"
additional:
noma: "urn:oid:1.3.6.1.4.1.20613.2.1.8"
anneeetude: "urn:oid:1.3.6.1.4.1.20613.2.1.9"
A typical additional fields dict could therefore be:
{"noma": "28581100", …

Store additional fields

---

inginious/frontend/app.py
inginious/frontend/pages/lti.py
inginious/frontend/parsable_text.py

Using links or images in the description of tasks and serving them over LTI doesn't work. This patch changes the RST HTML writer so that it rewrites relative URLs to use an intermediate page that will redirect the request to the correct asset URL using an HTTP 301.

Fix LTI relative urls

---

doc/install_doc/installation.rst

python35u-pip doesn't work on fresh centos 7 and centos 8. ( pip is not installed for some reason )
even if python3-pip installed instead,
installation of inginious will return this error 
```
#include <Python.h>
^
compilation terminated.
error: command 'gcc' failed with exit status 1
```
which needs python3-devel to work.
so i have replaced the installation command... 
I have also updated some web conf after testing on centos 8 and 7. (lighttpd)
however the documentation is missing some lighttpd permissions on some folders like /var/run/lighttpd and logs .. 
I didn't add those because any sys admin will figure them out easily.

updating Installation docs

---

base-containers/base/Dockerfile

Recently, in #520, the version of `msgpack-python` and `web.py` was specified for INGInious itself in version 0.6. For `msgpack-python`,  this is due to the release of version 1.0, which changes how encoding is handled. To allow the docker containers to communicate with INGInious, we must ensure that the same major version of the library is used for both the container and INGInious itself. This PR places the same restriction on the major version of the library in the base container, as was done for INGInious in #520. If this change is not performed, running all tasks, except mcq, will result in errors like this one
```
An internal error occurred. Please retry later. If the error persists, send an email to the course administrator. [Submission #5eb3da069949682704d3cb19]
The grader did not …
```

Specify version for msgpack-python in the Docker container

---

inginious/frontend/pages/course_admin/submissions.py
inginious/frontend/pages/course_admin/utils.py
inginious/frontend/templates/course_admin/submissions.html

Fixes Issue #523 
This adds a single checkbox to filter submissions that crashed or timed out.
Do you prefer a single checkbox like this or a radio group with three choices (i.e., timeout, crash, no filter)?

Submissions list: add a filter for crashes and timeouts

---

inginious/frontend/accessible_time.py
inginious/frontend/pages/course_admin/task_edit.py

Otherwise, it silently sets the soft deadline to the hard one and the user might think that it worked

Return error to user if form has invalid deadlines

---

inginious/frontend/pages/course.py
inginious/frontend/pages/course_register.py
inginious/frontend/pages/courselist.py
inginious/frontend/pages/marketplace.py
inginious/frontend/pages/marketplace_course.py
inginious/frontend/template_helper.py
inginious/frontend/templates/layout_jinja.html

* This allows to call subfolder when using use_jinja=True
* and will allow to simply remove get_renderer and get_custom_renderer when the migration is done.

Use another function to render jinja templates

---

inginious/backend/backend.py
inginious/common/messages.py

Previously, the client "job id" and the backend "job id" were different.
The backend job id was actually a tuple containing the address of the client and the jobid it gave.
A very simple form of authetication was then used to allow (or not) clients to access data or kill a job: the Backend job id must be the same (i.e. the request should come from the original client).
In practice, this is a safety guarantee that is never used (at least we never seen it used in the wild) and we have problem with uwsgi-like setups where multiple frontend processes (and thus clients...) are started.
This PR then simply modify the backend job id to be the one sent by the client. The client should thus ensure that the id created is unique. uuid4(), as currently done, should be sufficient.

Fix jobid handling

---

base-containers/base/bin/INGInious

When the agent crashes (it happens :-() the stdin will be in EOF state while we try to read... creating an infinite loop that apparently breaks the asyncio event loop, maybe because read returns instantly.

Fix endless loop in the containers when the agent crashes

---

inginious/frontend/pages/course.py
inginious/frontend/pages/course_admin/student_info.py
inginious/frontend/pages/tasks.py
inginious/frontend/task_dispensers/__init__.py
inginious/frontend/task_dispensers/combinatory_test.py
inginious/frontend/task_dispensers/toc.py
inginious/frontend/task_dispensers/util.py
inginious/frontend/templates/course_admin/student_info.html
inginious/frontend/templates/course_admin/task_dispensers/combinatory_test.html
inginious/frontend/templates/course_admin/task_dispensers/empty_section.html
inginious/frontend/templates/course_admin/task_dispensers/section.html
inginious/frontend/templates/course_admin/task_dispensers/section_config.html
inginious/frontend/templates/course_admin/task_dispensers/toc.html
inginious/frontend/templates/task_dispensers/task_list.html
inginious/frontend/user_manager.py

Pull request #605 has introduced some huge computational problems due to a raw refactor.
Problems:
- Student score computation is drastically reduced due to the ``task_is_visible`` function which was called T*U times, where T is the amount of course tasks and U the amount of user tasks. This function called the task dispenser ``filter_accessibility`` function that typically looped on the task list. In cases U=S*T where S is the amount of students in a course, the student score computation was done with an awful complexity of ST^3
- Visibility has become quite cahotic: the task listing looped on every task and checked if it could be displayed, resulting in another terrible complexity. Specific code had to be added at the task page code to allow admins to access the tasks that are not given …

Optimize task distribution and grade computation

---

inginious/frontend/task_dispensers/toc.py
inginious/frontend/templates/task_dispensers/task_list.html
inginious/frontend/templates/task_dispensers/toc.html

This allows Table of Contents sections to be shown closed by default. This was requested in August 2020.

Allow sections to be closed by default

---

base-containers/base/bin/inginious-ipython

By default, the variable __file__ is not defined when running a file with IPython
It gives the path to current source file
This PR defines the variable for the run file

Set __file__ variable when using IPython

---

inginious/frontend/plugins/auth/ldap_auth.py

Properly encoding `login` while formatting `ldap_request` will avoid a LDAP Injection which could allow an attacker to leak information and even bypass the authorization measures.
https://github.com/UCL-INGI/INGInious/blob/4d1a46f1e1df8b608a7bba715faa0b86aa0c18c1/inginious/frontend/plugins/auth/ldap_auth.py#L101

Fix LDAP Injection

---

doc/install_doc/config_reference.rst
doc/teacher_doc/course_admin.rst
inginious/frontend/plugins/upcoming_tasks/__init__.py
inginious/frontend/plugins/upcoming_tasks/templates/coming_tasks.html
inginious/frontend/plugins/upcoming_tasks/templates/main_menu.html
inginious/frontend/plugins/upcoming_tasks/templates/upcoming.html
inginious/frontend/plugins/upcoming_tasks/templates/upcoming_task_list.html

This adds the upcoming_tasks plugin as one of the default plugin in the inginious.frontend.plugins folder.
It is enabled by adding the following line in the configuration.yaml file:
` - plugin_module: "inginious.frontend.plugins.upcoming_tasks" `
It adds a "Upcoming tasks" button in the left menu (from the homepage without selecting a course) that leads to a new page.
This page displays the available unsuccessful tasks that have a deadline for courses the user is registered in.
The tasks are displayed by sections (one section per course).
The sections (courses) are ordered based on their closest deadline then the tasks themselves are ordered based on their deadlines.
A button on the right allows to display only tasks with deadlines in a specific range.
If you find any potential issue …

Adding the upcoming_tasks plugin

---

base-containers/base/bin/_run_student_intern

This error made the use of "ssh_student" with a python "run" script not correctly closing the student_container.
Actually it tried to run the teardown-script even if the string was None.
This issue, however, did not impact run_student nor ssh_student when using bash "run" script.
It should be merged ASAP.

hotfix ssh_student

---

inginious/frontend/flask/mongo_sessions.py
inginious/frontend/pages/lti.py
inginious/frontend/pages/utils.py
inginious/frontend/user_manager.py

This fixes erroneous code where session fetched was still the cookie one if available and never replaced. This resulted in displaying the same task on multiple-LTI-frame pages or more weird things according to the request sequence.
Moreover, Flask doesn't deal at all with session hotswap and its context stack, therefore the session manager creates the new session when it detects the LTI launch page is requested. Workaround code for some strange behaviours could then be removed.

lti/cookieless : correctly handle sessions

---

doc/dev_doc/extensions_doc/plugins.rst
inginious/frontend/template_helper.py
inginious/frontend/templates/course_admin/submission.html
inginious/frontend/templates/task_dispensers/task_list.html

This pull requests suggests adding two new hooks for the frontend: `submission_admin_menu` and `task_list_item`. 
Adding these hooks is motivated by my work on my plugin for adding custom coding style grades to submissions: https://github.com/PederHA/inginious-coding-style
The hooks are required in order to add the elements that are necessary for the plugin to display its custom elements. In order to understand the changes I am suggesting, I will try to explain their purpose and functionality.
This hook adds the ability for plugins to add HTML to the admin/tutor menu displayed at the top of a student submission.
_Example of adding a custom button ("Grade coding style") using `submission_admin_menu`._
**`course`**: `inginious.frontend.courses.Course`
The course the submission's task …

Add new hooks: `submission_admin_menu` & `task_list_item`

---

inginious/frontend/submission_manager.py

The patch will allow the client to access LTI information within a grading container.
"consumer_key" and "outcome*" fields are excluded for security reason.

Send LTI informatoin to the client

---

inginious/frontend/templates/course_admin/task_edit.html

This follows #703 that introduced HTML char escaping issues in Javascript strings (<,>, "). In particular, a closing ``</script>`` markup inside a JS string actually stop JS interpreter.
This way, the dict is dumped into JSON format in the Python code to keep the exercises order in the OrderedDict, and the ``tojson`` Jinja filters applies the appropriate escaping that works with ``JSON.parse``.

course_admin/task_edit: fix HTML escaping issues

---

inginious/frontend/templates/course_admin/edit_tabs/basic.html

Else it will fail as ``task_data.get('author',[])`` will return ``None``.

course_admin/task_edit: allows yaml author field to be empty

---

inginious/frontend/accessible_time.py

By default, when putting no soft_deadline, it was encoding a dummy value (in year 9999) and raised an error message since soft_deafline can not be after hard_deadline.
Now, if soft_deadline was not encoded (or is after hard_deadline), it will simply be equal to the hard_deadline.
Implements issue #615

No soft_deadline required

---

inginious/frontend/app.py

Added an index on "status" to make "update_pending_jobs" faster (takes time filtering on the submission status at every inginious restart).
Also changed "ensure_index" to "create_index" since the first one was depricated since pymongo 3.0

DB status index

---

inginious/common/filesystems/local.py

Adding a trailing slash at the end of the parent prefix is not required since the \_\_init\_\_ method of the parent LocalFSProvider already did it.
https://github.com/UCL-INGI/INGInious/blob/8d49326d6e73ce887519dff518735d709c099685/inginious/common/filesystems/provider.py#L35-L39

LocalFSProvider: remove slash addition in from_subfolder

---

inginious/backend/backend.py

Namedtuple ``_replace`` function returns a new instance. Therefore, ``job.msg`` is never set to ``None`` is the waiting list, resulting in exceptions during the queue update after reserving an agent execution slot, never releasing it. The only way to recover is to restart the backend, or, in the best case, the agent.
This proposes a fix that directly removes the job from the waiting list and check if it's still there after popping the job id from the priority queue.

Fix denial of service by job deletion

---

inginious/frontend/installer.py

Pymongo 4.0+ introduced a new way to compare with database objects (see https://github.com/mongodb/mongo-python-driver/pull/728/files#diff-fea5af5b145e4376d3484eb5d647c0fd219bad8f07af1bae72de75ae3c1eba08).
This produces the following error in the "inginious-install" script:
```
Traceback (most recent call last):
File "./inginious-install", line 19, in <module>
inginious.frontend.installer.Installer(args.file).run()
File "/inginious/inginious/frontend/installer.py", line 148, in run
mongo_opt = self.configure_mongodb()
File "/inginious/inginious/frontend/installer.py", line 338, in configure_mongodb
if self.try_mongodb_opts(host, database_name):
File "/home/vagrant/.local/lib/python3.8/site-packages/pymongo/database.py", line 829, in __bool__
raise NotImplementedError("Database objects do …
```

[installer] Fix failure due to pymongo bump

---

base-containers/base/inginious_container_api/run_student.py

``run_student`` behaviour has changed in PR #700 so that the current ``wait_until_finished`` function wraps a file around stdout and sdterr file descriptors. However, by default, when the file is deallocated at the end of the function, the file descriptor is also closed.
This leads to a ``Bad file descriptor`` errors when ``run_student_simple`` closes its pipe (https://github.com/UCL-INGI/INGInious/blob/master/base-containers/base/inginious_container_api/run_student.py#L134) as its ``std_out_w`` has been closed in the meantime :
sendmsg(21, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="S", iov_len=1}], msg_iovlen=1, msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_RIGHTS, cmsg_data=[7, 4, 6]}], msg_controllen=32, msg_flags=0}, 0) = 1
sendto(21, …

[containers/run_student] Keep std file descriptors open in wait_until_finished

---

inginious/frontend/templates/course_admin/student_list.html

As user_data only contains students, it's unnecessary to subtract admins.

[Frontend / Course Admin] Bad student count.

---

inginious/agent/__init__.py
inginious/agent/docker_agent/__init__.py
inginious/agent/mcq_agent/__init__.py
inginious/backend/backend.py
inginious/common/messages.py

The fix for #743  is done at the agent level, as it is not easy to know if the previous state has to be used at the queue level based on the received information as the state can legitimately be empty.

[backend] do not erase previous state in case of errors

---

inginious/frontend/static/js/task.js

To avoid connection rejections due to clients using preferentially public key authentications, leading to "Too many authentication failures" error

add ssh option to use password authentication by default

---

inginious/frontend/templates/course_admin/subproblems/file.html

Apparently space do not work, extensions must be separated by commas (which is more usual. Am I the only one to follow the doc? :p)

File extensions must be separated by commas

---

inginious/backend/backend.py

**Describe the bug**
In database-shared multi-client (multiprocess) setup, another client can kill a waiting job it does not own and receive a JobDone it cannot process. This PR aims at fixing this by sending the message to the initiating client.
**INGInious installation details**
- Version: v0.5+
**To Reproduce**
Steps to reproduce the behavior:
1. Deploy webapp, queue and agent with `concurrency=1` separately.
2. Deploy a second webapp using the same configuration file.
3. Submit a long processing job (sleep for instance) so that the agent gets busy.
4. In the meantime, submit a job for another task so that a job is in the waiting list.
5. Kill that job from the second webapp instance, you'll get something like:
Traceback (most recent call last):
File …

[backend] BackendJobDone should be sent to the waiting job initiating client

---

inginious/agent/docker_agent/_docker_interface.py
setup.py

Since Docker 23, container image creation date seem to include the timezone. Moreover, previous creation date strings remain unchanged. Example :
>>> for im in client.images.list():
...     print(im.attrs["Created"])
...
2023-02-23T09:34:58.109950958+01:00
2023-02-23T09:34:58.109950958+01:00
2023-02-02T05:09:14.349840104Z
2022-05-12T18:22:55.007415828Z
2022-03-15T22:20:23.996544531Z
2021-09-15T18:20:23.99863383Z
This breaks current code which removes the last 4 chars. Complete isodate support in Python is too recent (3.11) to replace it by ``datetime.fromisoformat``. Another quick solution is to take the 26 first chars.
However, the docker API includes since v3.0 a `history()` function that returns image layers creation time using a timestamp directly. The first one always seems to be the …

[docker_agent] fix container timestamp for docker 23+

---

inginious/frontend/pages/course_admin/search_user.py

This PR resolves #907 by proposing extra filters on  user list query.
Additional context of #907 remains relevant as this PR only hides users and does not treat problem of no username users.

Filter non activate and "empty username" users.

---

inginious/frontend/submission_manager.py

Fixes #697.
This is a first mitigation and in all case useful, as the limit is set on the total command sent to the MongoDB server, which cannot be computed before.
Do not update user stats in case of error.
Runfile to test : 
#!/bin/bash
dd if=/dev/random of=test.out bs=4M count=100
cat test.out | tr -dc '[:alpha:]' | feedback-msg -a
feedback-result success

[frontend/submission_manager] catch DocumentTooLarge exception

---

doc/teacher_doc/course_tuto.rst
doc/teacher_doc/task_tuto.rst
inginious/frontend/installer.py

The demo tasks repository has been moved to the new INGInious organisation. See https://github.com/INGInious/demo-tasks

Update demo tasks repo URL to new organisation

---

inginious/frontend/task_dispensers/__init__.py
inginious/frontend/task_dispensers/combinatory_test.py
inginious/frontend/task_dispensers/toc.py
inginious/frontend/task_dispensers/util.py
inginious/frontend/templates/course.html
inginious/frontend/templates/task_dispensers/task_list.html
inginious/frontend/templates/task_dispensers/toc.html

This PR proposes an extension of section configuration by adding an "hidden" item to simply hide a section.
It doesn't influence calculation of scores which remains for discussion:
Does this feature should influence score or does it simply hide a section for a user.
Done in this PR:
- Addition of an "hidden" config for a section
- Update of templates to hide a section if the config is set to True.
Once merged, this PR resolves #914 and #433

Adding "hidden" config item to Section

---

inginious/common/tasks_problems.py
inginious/frontend/app.py
inginious/frontend/pages/course_admin/task_edit.py
inginious/frontend/static/js/common.js
inginious/frontend/static/js/studio.js
inginious/frontend/task_problems.py
inginious/frontend/templates/course_admin/subproblems/code.html
inginious/frontend/templates/tasks/code.html

This PR adds the possibility through the task edit form to have a line offset for the code blocks in code problems. Adding a field to the form, checking it's value and applying the changes to the particular problem. An error will be displayed if the user inputs something other than a number.

[Frontend] Adding line offset for code problems

---

inginious/frontend/installer.py
inginious/frontend/pages/course_admin/danger_zone.py
inginious/frontend/pages/preferences/profile.py
inginious/frontend/pages/register.py
inginious/frontend/user_manager.py
setup.py

Related to issue #358 
This pull request contains changes regarding multiple elements : 
- Adding a new hashing function hash_password_argon2id and renaming the old one to hash_password_sha512.
- Supporting user authentication regardless of the algorithm hashing their password in the database. 
- Using the argon2 hash for new users (via self registering, administrator registering or during the installation process).
- Using the argon2 hash when a users resets it's password or changes it
Password hashes with argon2id are now stored in the database using a prepend "argon2id-" to allow future changes.

[frontend] Adding the use of Argon2id for password hashing

---

doc/admin_doc/install_doc/installation.rst
setup.py

Updating documentation for ubuntu 24.04 and adding requests version in requirements (needed for docker)

Update documentation and setup.py requirements

---

doc/teacher_doc/task_tuto.rst

This is a PR to solve an issue related to the doc.
Looking at the tutorial of how to write an hello world exercise, it stated an example of the code to put in a template file to run the student code.
The problem is that the student code is inside the function and the funtion was called at the end of the function instead of being called after the function definition. This would result in not being able to run the student code but even by running the function it will be an infinite loop. 
To solve this, I had to remove one indentation level as Python works with identation at the right level to call a function. By testing, the code was indeed showing nothing before the change and displayed "hello world" after changes.

Fix - removed indentation in tutorial

---

inginious/frontend/pages/api/courses.py
inginious/frontend/pages/api/submissions.py
inginious/frontend/pages/api/tasks.py
inginious/frontend/pages/group.py
inginious/frontend/pages/utils.py
inginious/frontend/plugins/contests/__init__.py
inginious/frontend/plugins/simple_grader/__init__.py
inginious/frontend/plugins/upcoming_tasks/__init__.py

During a refactoring in order to get rid of the course_factory, some "course_factory" were replaced by "taskset_factory" and should not have been.
This PR simply restores the right variables.

fix typo regarding refactoring from course_factory to taskset_factory

---

setup.py

This PR has as goal to set the package dependencies to exact versions as well as impose the 2.3.7 version of Werkzeug to avoid the reoccurring dependency problem related (see #1013).

V0.8 dependecies fix

---

COPYRIGHTS
setup.py

This contribution aims to solve a problem at the installation of INGInious due to an update in a library.
When installing INGInious by using the `docker compose up --builder` command, an error occurs at the end of the installation :
1) Clone the repository
2) Launch the command : `sudo docker compose up --builder`
It appears that the problem is because the package `setuptools_scm` received a new version (8.2.0) that breaks the installation of INGInious.
One solution is to fix the version to the previous one where the installation was working (8.1.0). By setting it in `setup.py`, the installation is now working.

fix(setup): hardcoded stable version of setuptools_scm

---

doc/admin_doc/install_doc/create_container.rst

The previous project's container registry was DockerHub but we moved to the Github registry. Documentation has not been updated to reflect that change.
The nomenclature of environment containers also has been updated from `inginious-c-<env name>` to `env-<env name>`.
This fixes #1056.

doc/create_container: Replace old environments registry

---

inginious/frontend/pages/course_register.py

This pull request proposes a fix for issue #1018 .
basic_checks always return a tuple of two values.
redirect is handled in GET method.

force two values in return and handle redirect outside of function
